package service;

import model.Transaction;
import model.TransactionItem;

import java.util.List;

public class InvoiceService {

    public void printInvoice(Transaction tx, List<TransactionItem> items) {
        System.out.println("\n========================================");
        System.out.println("                INVOICE                 ");
        System.out.println("========================================");
        System.out.println("Order ID    : " + tx.getId());
        // We might not have the date in tx if it just got generated by DB, so skip or show generic info
        System.out.println("----------------------------------------");
        System.out.printf("%-20s %-10s %-10s\n", "Item Name", "Quantity", "Price");
        System.out.println("----------------------------------------");
        
        for (TransactionItem item : items) {
            System.out.printf("%-20s %-10d $%-9.2f\n", 
                    item.getProductName(), item.getQuantity(), item.getPrice());
        }
        
        System.out.println("----------------------------------------");
        System.out.printf("TOTAL AMOUNT: $%.2f\n", tx.getTotalAmount());
        System.out.println("========================================\n");
    }
}
